---

- name: download tarball with checksum
  get_url:
    url: "{{ julia_url }}"
    dest: "/tmp/{{ julia_basename }}.tgz"
    checksum: "sha256:{{ julia_checksum_url }}"
  register: tarball

- name: "unarchive under {{ julia_dir }}"
  unarchive:
    src: "{{ tarball.dest }}"
    dest: "{{ julia_dir }}"

- name: install julia
  file:
    state: link
    src: "{{ julia_dir }}/{{ julia_basename }}/{{ item }}"
    dest: "{{ julia_install_path }}/{{ item }}"
  with_items:
    - bin/julia
    - share/man/man1/julia.1
